In [ ]:
Coding Challenges: Chapter 4
Nishan Karki
BINF 3360
Computational Biology
Date: 03/14/2022

# 4.5 STEP 10

In [22]:
%time
import os

def make_change(money, coins):
    money_coins = [0]*(money + 1)
    
#     print(money_coins)
#     print(len(coins))
    
    for e_money in range (1, money+1):
        money_coins[e_money] = 9999999
        for i in range (len(coins)):
            if e_money >= coins[i]:
                if money_coins[e_money - coins[i]] + 1 < money_coins[e_money]:
                        money_coins[e_money] = money_coins[e_money - coins[i]] + 1
                        
    return money_coins[money]
        

def main():
    money = 16431
    coins = [18,15,14,10,8,5,3,1]
    
    print(make_change(money, coins))
    
if __name__ == '__main__':
    main()

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 8.82 µs
913


# 4.6 STEP 10

In [129]:
%time
import os
import numpy as np

def ManhattanTourist(n, m, down, right):
    
    s = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
#     print(len(s))
    
    for i in range (1, n+1):
        s[i] [0] = s[i-1][0] + down[i-1] [0]
    for j in range (1, m+1):
        s[0] [j] = s[0] [j-1] + right[0] [j-1]
    print(s)
    for i in range (1, n+1):
#         print(str(i) + "----")
        for j in range (1, m+1):
#             print(j)
#             print(s[i][j])
            s[i] [j] = max(s[i-1] [j] + down[i-1] [j], s[i] [j-1] + right[i] [j-1])
    print(s)
    return s[n, m]

def main():
    
    with open('/Users/nises/Downloads/dataset_604480_10.txt') as input_data:
#         n = int((input_data.readline()).translate('\n'))
#         m = int((input_data.readline()).translate('\n'))
        n, m = map(int,input_data.readline().strip().split(' '))
        p = n*m
        down = []
        right = []
        
        for i in range(n):
            down.append(list(map(int,input_data.readline().strip().split(' ')))) 
            
        input_data.readline().strip().split(' ')
        
        for i in range(n+1):
            right.append(list(map(int,input_data.readline().strip().split(' '))))
        
#     print(down)
#     print(right)
    
#     n = 4
#     m = 4
#     p = n*m
    
#     down = np.array([0]*20).reshape(4,5)
#     down[0][0], down[0][1], down[0][2], down[0][3], down[0][4] = 1,0,2,4,3
#     down[1][0], down[1][1], down[1][2], down[1][3], down[1][4] = 4,6,5,2,1
#     down[2][0], down[2][1], down[2][2], down[2][3], down[2][4] = 4,4,5,2,1
#     down[3][0], down[3][1], down[3][2], down[3][3], down[3][4] = 5,6,8,5,3
    
#     right = np.array([0]*20).reshape(5,4)
#     right[0][0], right[0][1], right[0][2], right[0][3]= 3,2,4,0
#     right[1][0], right[1][1], right[1][2], right[1][3]= 3,2,4,2
#     right[2][0], right[2][1], right[2][2], right[2][3]= 0,7,3,3
#     right[3][0], right[3][1], right[3][2], right[3][3]= 3,3,0,2
#     right[4][0], right[4][1], right[4][2], right[4][3]= 1,3,2,2
    
    print(ManhattanTourist(n, m, down, right))
    
if __name__ == '__main__':
    main()

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.01 µs
[[ 0  3  6  6  8  9  9 10 11 11 11 13 17 19 19 22 23]
 [ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
[[ 0  3  6  6  8  9  9 10 11 11 11 13 17 19 19 22 23]
 [ 2  5 10 13 14 16 19 23 25 25 29 29 30 34 38 38 41]
 [ 6  7 11 15 19 23 26 30 33 35 39 43 46 47 51 53 54]
 [ 8 12 14 19 20 26 29 33 37 40 41 46 50 51 52 55 58]
 [11 14 14 20 24 28 31 33 39 44 44 49 53 55 59 61 65]
 [12 18 19 23 26 

# 4.8 STEP 5

In [196]:
def LCSBackTrack(v, w):
    n = len(v)
    m = len(w)
    s = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
    Backtrack = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
    
#     for i in range (1, n+1):
#         s[i][0] = 0
#     for j in range (1, m+1):
#         s[0][j] = 0
        
    for i in range (1, n+1):
        for j in range (1, m+1):
            if v[i-1] == w[j-1]:
                s[i][j] = max(s[i-1][j] , s[i][j-1] , s[i-1][j-1] + 1)
            else:
                s[i][j] =max(s[i-1][j], s[i][j-1])
                
            if s[i][j] == s[i-1][j]:
                Backtrack[i][j] = "1" #down
                
            elif s[i][j] == s[i][j-1]:
                Backtrack[i][j] = "2" #right
                
            elif s[i][j] == s[i-1][j-1] + 1:
                Backtrack[i][j] = "3" #diag
    return Backtrack

lcs = []
def OutputLCS(backtrack, v, i, j):

    if i == 0 or j == 0:
        return
    if backtrack[i][j] == 1:
        OutputLCS(backtrack, v, i - 1, j)
    elif backtrack [i][j] == 2:
        OutputLCS(backtrack, v, i, j - 1)
    else:
        OutputLCS(backtrack, v, i - 1, j - 1)
        lcs.append(v[i-1])
        
#     print(lcs)

    return lcs


def main():
    
    with open('/Users/nises/Downloads/dataset_604482_5.txt') as input_data:
        v = input_data.readline().strip()
        w = input_data.readline().strip()
    
#     print(v)
    backtrack = LCSBackTrack(v,w)
#     print(backtrack)
    answer = OutputLCS(backtrack, v, len(v), len(w))
    print ("".join(answer))
    
if __name__ == '__main__':
    main()

CTCCTACACTTCTTTTAACGTGCCTTGGATTTTGCTTTAAAAGTAGTACAGTTTCCGTGCTTTGGTAGGGCTCACAGATTATCCCACTTTGCAACACTGGCCGCCGGTTTCCCCCTAGGTTTCTCGTAACTTGGGACTGAGTTTCTCATAGGGGCGGCTGTTTGTGGGGACGGCGTTGCTTTACCCTTAATCAAAAGTTGTGTGCCGACTAAGCTGGGGGGGGGCGCCTGGGGATGACAATTTTTCAGGCCCTCACTTGTCGGTTAACTTTTATGGGTAAAAATTGCGCCAGCGCCTACCTTACTGGGCTGACTCTGTCTATGTAGCATGACGGACCATATAGGAGACACAGGTACATAAGAGAGATCGAGTGAGCTTAGCTGGAAAAAAGATATTTGGAGTAAGAGGTCTGTGATGACGAGCCGAGTGTATTACTAGGTCATAAAGGGTTCGGTTCCCCAGCAGTTTCAGGCTTTCACCACGTCCGCGGAACTAATCTCATATCAGAAGCCACCAAGTTCCGCCTTTGAAACTTCGCACCCCAATACCTGAATAATCACGTCTGGCGAGGGACAAGACATCCAGCAGTTCAACCTTGGAATCCGTTTCTGG


# 4.8 STEP 7

In [36]:
import networkx as nx

def longest_dag(ed, s_n, e_n):
    d_graph = nx.DiGraph()
    edges = ed
#     edges = [(0,1,{'weight':7}), (0,2,{'weight':4}), (2,3,{'weight':2}), (1,4,{'weight':1}), (3,4,{'weight':3})]
    d_graph.add_edges_from(edges)
#     print(edges)

    paths = nx.all_simple_paths(d_graph, source=s_n, target=e_n)
    # print(list(paths))

    all_paths = []
    for path in paths:
        all_paths = list(set(all_paths + path))
#     print(all_paths)

    for edge in edges:
    #     print(edge)
        if ((edge[0] not in all_paths) | (edge[1] not in all_paths)):
            d_graph.remove_edge(*edge[:2])
#     print(d_graph)

    wt = nx.dag_longest_path(d_graph, weight="weight")
    l_path = nx.dag_longest_path_length(d_graph, weight="weight")

    print(l_path)
#     print(wt)
    return wt

def main():
    with open('/Users/nises/Downloads/dataset_604482_7.txt') as input_data:
        lines = input_data.read().splitlines()
                  
    s_n = int(lines[0])
    e_n = int(lines[1])
    edges = []
    
    for line in lines[2:]:
        a = int(line.split("->")[0])
        b = int(line.split("->")[1].split(':')[0])
        w = int(line.split("->")[1].split(':')[1])
        edge = (a,b,{'weight':w})
        edges.append(edge)

#     print(e_n)
    answer = longest_dag(edges, s_n, e_n)
    answer = map(str, answer)
    print ("->".join(answer))
    
if __name__ == '__main__':
    main()

226
0->1->3->4->5->9->10->12->13->14->19->20->25->26->27->29->46->47->48->49


# 4.10 STEP 3

In [5]:
import sys
import numpy as np
import os
from Bio.Align import substitution_matrices

def calc_scores(s1, s2, s_matrix, pen):
    
    n = len(s1)
    m = len(s2)

    s = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
    backtrack = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
    
    for i in range (1, n+1):
        s[i][0] = -i * pen
        
    for j in range (1, m+1):
        s[0][j] = -j * pen
    
#     print(s)
#     print(backtrack)
    
    for i in range(1, n+1):
        for j in range(1, m+1):
            scores = [s[i-1][j] - pen, s[i][j-1] - pen, s[i-1][j-1] + s_matrix[s1[i-1], s2[j-1]]]
            s[i][j] = max(scores)
            
            if s[i][j] == s[i-1][j]-pen:
                backtrack[i][j] = "0"
                
            elif s[i][j] == s[i][j-1]-pen:
                backtrack[i][j] = "1"
                
            elif s[i][j] == s[i-1][j-1] + s_matrix[s1[i-1], s2[j-1]]:
                backtrack[i][j] = "2"
    
    print(s)
    score = (s[n][m])
    return backtrack, score
    # 0 insert/right, 1 del/down, 2 match/mismatch


def OutputGA(backtrack, v, w, i, j):
    alignment1 = []
    alignment2 = []
#     print(i)
#     print(j)
#     print(backtrack [i-2][j-2])
    
    while i > 0 or j > 0:
        if backtrack [i][j] == 2:
            alignment1.append(v[i-1])
            alignment2.append(w[j-1])
            i -= 1
            j -= 1
#             print(backtrack [i][j])
#             print(i)
#             print(j)
            
        elif backtrack[i][j] == 1:
            alignment1.append('-')
            alignment2.append(w[j-1])
            j -= 1
#             print(backtrack [i][j])
            
        elif backtrack[i][j] == 0:
            alignment1.append(v[i-1])
            alignment2.append('-')
            i -= 1
#             print(backtrack [i][j])
            
#     alignment1 = alignment1.reverse()
#     alignment2 = alignment2.reverse()
    
    alignment1 = alignment1[::-1]
    alignment2 = alignment2[::-1]
#     print(alignment1[::-1])
#     print(alignment2[::-1])

    return alignment1, alignment2
            

if __name__ == '__main__':
    with open('/Users/nises/Downloads/dataset_604484_3.txt') as f:
        str1 = f.readline().strip()
        str2 = f.readline().strip()

#     str1 = 'PLEASANTLY'
#     str2 = 'MEANLY'

#     print(str1)
        

    scoring_matrix = substitution_matrices.read('/Users/nises/Desktop/score_matrix.txt')
        
#         lines = input_data.read().splitlines()
    
        
#     print(scoring_matrix)
    
    penalty = 5
    bt, score = calc_scores(str1, str2, scoring_matrix, penalty)
    print(score)
    a1, a2 = OutputGA(bt, str1, str2, len(str1),len(str2))
    print ("".join(a1))
    print ("".join(a2))

[[    0    -5   -10 ... -4690 -4695 -4700]
 [   -5    -1    -6 ... -4678 -4683 -4688]
 [  -10    -6    -3 ... -4665 -4670 -4675]
 ...
 [-4295 -4286 -4276 ...  2385  2383  2378]
 [-4300 -4291 -4281 ...  2380  2390  2385]
 [-4305 -4296 -4286 ...  2375  2385  2394]]
2394
Y--HD-E---ES-F-P-H-Y-E-E-V-V-N-------N--L-Q-Q-E-C-Q-S-V-F-R-M-C--E------V-S-V-K-L-H-M-R-M----Y-SL-E-P--YQ-P-R-G-N-S---A-Y----LM-H-I-Y-G---M-D-H-H-H-H-I---D---VY--N----T-R-R-K-K-H-------Y--F--V-AE--WPW-D-RILV-H-Q-Y-S-L-C---P-D-K-S-C-Q-F-C-T-M-S-C-E-P-Q-I-A-A-P-S-L-G-IGHNWI-A-N-T-L-H-E--YF-H-Q-I-V-Y-A-S-Q-N-M-N-W-I-E-Y-F-F-E-K-S---N------G-R--RT-F-N-F-Y-N-W-V--ER-F-S-SKMFG-L-K-Y-V-W-S-N-C-Q--TS---LLY-P-T-M-F-V-S-E-Y-N-R------T----F-D-C-Q-V-Y-F-F-F---H--PKQ--I-S-QV--E-TD--MV-I-Y-W-T-V-K-R-P-I-L-G-T-T-L-H-F-P---------Q-K-N--CM-EW--R-R-TMCV-A-C-H-I-K--CTDAC-I-P-N-Q-P-R-R-Y-V-W-C-L-T-E-Y-G-L-S-R-G---LT-G-N-M-E-W-Q-Q----H-M-T-F-A-V-H-A-M----H-F-FNNS-G-S-V-V--CM-HRQEW-D-I-F-A-V-G-K-E-N-K-I-R-K--G--Y--M-CCQA-V--N-N-H-G-C-M-PMYY-H-

# 4.10 STEP 10

In [36]:
import sys
import numpy as np
import os
from Bio.Align import substitution_matrices

def calc_scores(s1, s2, s_matrix, pen):
    
    n = len(s1)
    m = len(s2)

    s = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
    backtrack = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
    
    for i in range (1, n+1):
        s[i][0] = -i * pen
        
    for j in range (1, m+1):
        s[0][j] = -j * pen
    
#     print(s)
#     print(backtrack)
    
    for i in range(1, n+1):
        for j in range(1, m+1):
            scores = [s[i-1][j] - pen, s[i][j-1] - pen, s[i-1][j-1] + s_matrix[s1[i-1], s2[j-1]], 0]
            s[i][j] = max(scores)
            
            if s[i][j] == s[i-1][j]-pen:
                backtrack[i][j] = "0"
                
            elif s[i][j] == s[i][j-1]-pen:
                backtrack[i][j] = "1"
                
            elif s[i][j] == s[i-1][j-1] + s_matrix[s1[i-1], s2[j-1]]:
                backtrack[i][j] = "2"
                
            elif s[i][j] < 0:
                backtrack[i][j] = "4"
    
    print(s)
    print(backtrack)
    score = (s[n][m])
    return backtrack, score, s
    # 0 insert/right, 1 del/down, 2 match/mismatch


def OutputGA(backtrack, v, w, i, j, s):
    alignment1 = []
    alignment2 = []

#     print(i)
#     print(j)
#     print(backtrack [i-1][j-1])
    
    while(i > 0 or j > 0) and (s[i, j] > 0):
        if backtrack [i][j] == 2:
            alignment1.append(v[i-1])
            alignment2.append(w[j-1])
#             print(backtrack [i][j])
            i -= 1
            j -= 1
#             print(backtrack [i][j])
#             print(i)
#             print(j)
            
        elif backtrack[i][j] == 1:
            alignment1.append('-')
            alignment2.append(w[j-1])
            j -= 1
            
        elif backtrack[i][j] == 0:
            alignment1.append(v[i-1])
            alignment2.append('-')
            
#             print(backtrack [i][j])
            i -= 1
            
#     alignment1 = alignment1.reverse()
#     alignment2 = alignment2.reverse()
    
    alignment1 = alignment1[::-1]
    alignment2 = alignment2[::-1]
#     print(alignment1[::-1])
#     print(alignment2[::-1])

    return alignment1, alignment2
            

if __name__ == '__main__':
    with open('/Users/nises/Downloads/dataset_604484_10.txt') as f:
        str1 = f.readline().strip()
        str2 = f.readline().strip()

#     str1 = 'PLEASANTLY'
#     str2 = 'MEANLY'

#     print(str1)
        

    scoring_matrix = substitution_matrices.read('/Users/nises/Desktop/score_matrix.txt')
        
#         lines = input_data.read().splitlines()
    
        
#     print(scoring_matrix)
    
    penalty = 5
    bt, score, s = calc_scores(str1, str2, scoring_matrix, penalty)
    print(score)
    a1, a2 = OutputGA(bt, str1, str2, len(str1),len(str2), s)
    print ("".join(a1))
    print ("".join(a2))

[[    0    -5   -10 ... -4625 -4630 -4635]
 [   -5     0     0 ...     0     0     0]
 [  -10     0     0 ...     3     3     0]
 ...
 [-4490     0     0 ...  1209  1208  1204]
 [-4495     0     0 ...  1208  1203  1203]
 [-4500     0     0 ...  1214  1209  1204]]
[[0 0 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 [0 0 2 ... 2 2 0]
 ...
 [0 0 2 ... 2 2 2]
 [0 0 0 ... 1 0 2]
 [0 0 2 ... 2 1 1]]
1204
HKWQ---WFICCFHSNHIDPTVLKSGWDHRCMNQ-WCGGQGQS-PLSDMQCLDSIFK-LQ-PPN-DY-IP--C---I-WWYSGWKCQHWTPFRFTIVQL-CSYGNAYVKNSWNRLEP-DYWVTNY-IKHP-PWAILFKADGA-SWRIVQVAGYM-WYNEVPMSWTRKTQFCQPRQQSECVFMQQPVIDSIYICDSTMNCVHGKGVVVMGPQPQE-T-AACVQLKEMIWCCWMQTPEDV-LS-KCCLPKYARFHIALEIVHDWMETTYEQQ-DYTTYSDHTTYHADDMIWNPRMAMDVFNHNVPDTN-QFVRCPSSDAFKNALVRK-HCMGASYSAHTTYVDECIYNRVRQAIQQKIRWDQFFRYLYYSM-HV-P-HSTY-MWKDH---Y-QK--F-WQTVKSSCKFHCTMENVRMNCM-L---AYWCFEAPESCAREIGDEWESTDRM-NPV-YD-----NQGRKKFNIKCVWVIK-L-MRPYAQTGYEQCCEIKRSRLDYDQPIYCCLFVALVEI---E-------G-VNCERFPLKVVSPADSARQCFSIGDYHAYKDQIKNAMPQILTQNALQFRHHDLLEHVRYCIKNMFQCFWQECRPNTKHNVHF

# 4.11 STEP 3

In [16]:
import sys
import numpy as np
import os
from Bio.Align import substitution_matrices

def calc_scores(s1, s2, pen):
    
    n = len(s1)
    m = len(s2)

    s = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
    backtrack = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
    
    for i in range (1, n+1):
        s[i][0] = i * pen
        
    for j in range (1, m+1):
        s[0][j] = j * pen
    
    
    for i in range(1, n+1):
        for j in range(1, m+1):
            
            if s1[i - 1] == s2[j - 1]:
                mw_score = s[i - 1][j - 1]
            else:
                mw_score = s[i - 1][j - 1] + pen
            
            scores = [s[i-1][j] + pen, s[i][j-1] + pen, mw_score]
            s[i][j] = min(scores)
            
    print(s)
    score = (s[n][m])
    print(score)
    
    return score, s


if __name__ == '__main__':
    with open('/Users/nises/Downloads/dataset_604485_3.txt') as f:
        str1 = f.readline().strip()
        str2 = f.readline().strip()

#     str1 = 'PLEASANTLY'
#     str2 = 'MEANLY'

#     print(str1)
        
    
    penalty = 1
    score, s = calc_scores(str1, str2, penalty)

[[  0   1   2 ... 747 748 749]
 [  1   0   1 ... 746 747 748]
 [  2   1   0 ... 745 746 747]
 ...
 [774 773 772 ... 353 354 355]
 [775 774 773 ... 354 353 354]
 [776 775 774 ... 355 354 353]]
353


# 4.11 STEP 5

In [63]:
import sys
import numpy as np
import os
from Bio.Align import substitution_matrices

def calc_scores(s1, s2, pen):
    
    n = len(s1)
    m = len(s2)

    s = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
    backtrack = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
    
#     for i in range (1, n+1):
#         s[i][0] = -i * pen
        
    for j in range (1, m+1):
        s[0][j] = -j * pen
    
#     print(s)
#     print(backtrack)
    
    for i in range(1, n+1):
        for j in range(1, m+1):
            
            if s1[i - 1] == s2[j - 1]:
                mw_score = s[i - 1][j - 1] + pen
            else:
                mw_score = s[i - 1][j - 1] - pen
            
            scores = [s[i-1][j] - pen, s[i][j-1] - pen, mw_score]
            s[i][j] = max(scores)
            
            if s[i][j] == s[i-1][j]-pen:
                backtrack[i][j] = "0"
                
            elif s[i][j] == s[i][j-1]-pen:
                backtrack[i][j] = "1"
                
            elif s[i][j] == mw_score:
                backtrack[i][j] = "2"
    
    print(s)
    
    max_score = []
    for i in range(0, n + 1):
        max_score.append(s[i][m]) 
    
#     print(max(max_score))
#     print(max_score)
    
#     max_row = []
#     for i in range(len(max_score)):
#         if (max_score[i] == max(max_score)):
#             max_row.append(i)
        
#     max_index = max(max_row)
    max_index = max_score.index(max(max_score))
#     print(max_index)
    score = (s[max_index][m])
    print(score)
    
    return backtrack, score, max_index


def OutputGA(backtrack, v, w, i, j):
    alignment1 = []
    alignment2 = []
#     print(i)
#     print(j)
#     print(backtrack [i-2][j-2])
    
    while j > 0:
        if backtrack [i][j] == 2:
            alignment1.append(v[i-1])
            alignment2.append(w[j-1])
            i -= 1
            j -= 1
#             print(backtrack [i][j])
#             print(i)
#             print(j)
            
        elif backtrack[i][j] == 1:
            alignment1.append('-')
            alignment2.append(w[j-1])
            j -= 1
#             print(backtrack [i][j])
            
        elif backtrack[i][j] == 0:
            alignment1.append(v[i-1])
            alignment2.append('-')
            i -= 1
#             print(backtrack [i][j])
            
#     alignment1 = alignment1.reverse()
#     alignment2 = alignment2.reverse()
    
    alignment1 = alignment1[::-1]
    alignment2 = alignment2[::-1]
#     print(alignment1[::-1])
#     print(alignment2[::-1])

    return alignment1, alignment2
            

if __name__ == '__main__':
    with open('/Users/nises/Downloads/dataset_604485_5.txt') as f:
        str1 = f.readline().strip()
        str2 = f.readline().strip()

#     str1 = 'GTAGGCTTAAGGTTA'
#     str2 = 'TAGATA'

#     print(str1)
    
    penalty = 1
    
    bt, score, max_row = calc_scores(str1, str2, penalty)
    a1, a2 = OutputGA(bt, str1, str2, max_row,len(str2))
    print ("".join(a1))
    print ("".join(a2))

[[  0  -1  -2 ... -92 -93 -94]
 [  0  -1  -2 ... -90 -91 -92]
 [  0  -1  -2 ... -88 -89 -90]
 ...
 [  0   0   1 ...   9  11  10]
 [  0  -1   0 ...   8  10  12]
 [  0   1   0 ...   7   9  11]]
23
GCGA-AAAAC--ACACC-AGAAGTAAACGTA--AG-GCCCTTACAT-TAGC-T-GGGG-AC-CGA--T-AG-GAAC-GTGTGAGTACAGATACTCATTC
G-GACAAAATGGA-AGCTAGT-GTCCACGAATTACCGCC-TTGCATCTAGGGTCGGGGTAGGCAAGCTTATCGAGCTGGGTGAGTACATATA-TCATCC


# 4.11 STEP 7

In [90]:
import sys
import numpy as np
import os
from Bio.Align import substitution_matrices

def calc_scores(s1, s2, pen):
    
    n = len(s1)
    m = len(s2)

    s = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
    backtrack = np.array([0]*((n+1)*(m+1))).reshape(n+1,m+1)
    
#     for i in range (1, n+1):
#         s[i][0] = -i * pen
        
#     for j in range (1, m+1):
#         s[0][j] = -j * pen
    
#     print(s)
#     print(backtrack)
    
    for i in range(1, n+1):
        for j in range(1, m+1):
            
            if s1[i - 1] == s2[j - 1]:
                mw_score = s[i - 1][j - 1] + 1
            else:
                mw_score = s[i - 1][j - 1] - pen
            
            scores = [s[i-1][j] - pen, s[i][j-1] - pen, mw_score]
            s[i][j] = max(scores)
            
            if s[i][j] == s[i-1][j]-pen:
                backtrack[i][j] = "0"
                
            elif s[i][j] == s[i][j-1]-pen:
                backtrack[i][j] = "1"
                
            elif s[i][j] == mw_score:
                backtrack[i][j] = "2"
    
    print(s)
    
    max_score = []
    for i in range(0, m + 1):
        max_score.append(s[n][i]) 
#         print(s[n][i])
    
#     print(max(max_score))
#     print(max_score)
    
#     max_row = []
#     for i in range(len(max_score)):
#         if (max_score[i] == max(max_score)):
#             max_row.append(i)
        
#     max_index = max(max_row)
    max_index = max_score.index(max(max_score))
#     print(max_index)
    score = (s[n][max_index])
    print(score)
    
    return backtrack, score, max_index


def OutputGA(backtrack, v, w, i, j):
    alignment1 = []
    alignment2 = []
#     print(i)
#     print(j)
#     print(backtrack [i-2][j-2])

#     print(i)
#     print(j)
    
    while j > 0:
        if backtrack [i][j] == 2:
            alignment1.append(v[i-1])
            alignment2.append(w[j-1])
            i -= 1
            j -= 1
#             print(backtrack [i][j])
#             print(i)
#             print(j)
            
        elif backtrack[i][j] == 1:
            alignment1.append('-')
            alignment2.append(w[j-1])
            j -= 1
#             print(backtrack [i][j])
            
        elif backtrack[i][j] == 0:
            alignment1.append(v[i-1])
            alignment2.append('-')
            i -= 1
#             print(backtrack [i][j])
            
#     alignment1 = alignment1.reverse()
#     alignment2 = alignment2.reverse()
    
    alignment1 = alignment1[::-1]
    alignment2 = alignment2[::-1]
#     print(alignment1[::-1])
#     print(alignment2[::-1])

    return alignment1, alignment2
            

if __name__ == '__main__':
    with open('/Users/nises/Downloads/dataset_604485_7.txt') as f:
        str1 = f.readline().strip()
        str2 = f.readline().strip()

#     str1 = 'PAWHEAE'
#     str2 = 'HEAGAWGHEE'
    
    penalty = 2
    
    bt, score, max_row = calc_scores(str1, str2, penalty)
    a1, a2 = OutputGA(bt, str1, str2, len(str1),max_row)
    print ("".join(a1))
    print ("".join(a2))

[[   0    0    0 ...    0    0    0]
 [   0   -2   -2 ...   -2   -2   -2]
 [   0   -2   -4 ...   -4   -4   -4]
 ...
 [   0   -2   -4 ... -330 -332 -334]
 [   0   -2   -4 ... -329 -331 -333]
 [   0   -2   -4 ... -329 -331 -333]]
46
GGTCCACACAAATTATGA--GGTTGTGT-CGAATTCGGCAGTTG-ATT-ACA-AG-ACGAGGCAATTCTC-TAAAAGCT-C-GTGCTCACCCTTAGCGTTAATCTGCTAT-AGCAA-AGCCGGCTCAG--AACCTAATGAG-TATC-GCAGGGCAACATGCCCG-CTCTATGTGCTAAGCT-AGTCTAATTGGCG-CTGG-CC-TGTTTCCCAGATAGCGCTCTTCTGCGTA--CGAGTGGAT-GCCGGTCGGTTAAAT
GGTTCATACACACTACGATCGGCTGCGTGCGAATTCGGCAGTCGTATTGACCGAGGACCAAGCA-TCCTCCTAAAA-CTTCCGTGCTCACT-TTAGAGTTGACCTG-T-TGACCAATAGCCCG-TCAGGGAATC-AATGGGGT-TCCGCTGGGCAAAATGTTCGTCTCC-TGCGCCAAGTTTAATTTAATTGGCGACTGAACCCTGTT-C--AGATAGCGCTCTTCTACGTAGGCGAATGGATAGCCTGTCGGTTAAA-


# END